services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_service

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"