services:
  reservation-service:
    build: ./reservation-service
    container_name: reservation-service
    environment:
      EUREKA_URL: http://eureka:8761/eureka
      SPRING_DATASOURCE_RESERVATION_URL: jdbc:postgresql://postgres-reservation:5432/reservation_db
      SPRING_SERVICES_USERNAME: admin
      SPRING_SERVICES_PASSWORD: admin123
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      ROUTING_KEY_EMPLOYEE_CREATED: employee.created
      ROUTING_KEY_EMPLOYEE_UPDATED: employee.update
      ROUTING_KEY_EMPLOYEE_DELETED: employee.deleted
      EXCHANGE_EMPLOYEE_NAME: employee.exchange
      ROUTING_KEY_ROOM_CREATED: room.created
      ROUTING_KEY_ROOM_UPDATED: room.update
      ROUTING_KEY_ROOM_DELETED: room.deleted
      EXCHANGE_ROOM_NAME: room.exchange
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_TIMEOUT: 60000
    depends_on:
      - eureka
      - rabbitmq
      - redis
      - employee-service
      - room-service
      - postgres-reservation
    ports:
      - "8081:8081"


  employee-service:
    build: ./employee-service
    container_name: employee-service
    environment:
      EUREKA_URL: http://eureka:8761/eureka
      SPRING_DATASOURCE_EMPLOYEE_URL: jdbc:postgresql://postgres-employee:5432/employee_db
      SPRING_SERVICES_USERNAME: admin
      SPRING_SERVICES_PASSWORD: admin123
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      ROUTING_KEY_EMPLOYEE_CREATED: employee.created
      ROUTING_KEY_EMPLOYEE_UPDATED: employee.update
      ROUTING_KEY_EMPLOYEE_DELETED: employee.deleted
      EXCHANGE_EMPLOYEE_NAME: employee.exchange
    depends_on:
      - eureka
      - rabbitmq
      - postgres-employee
    ports:
      - "8082:8082"
  
  room-service:
    build: ./room-service
    container_name: room-service
    environment:
      EUREKA_URL: http://eureka:8761/eureka
      SPRING_DATASOURCE_ROOM_URL: jdbc:postgresql://postgres-room:5432/room_db
      SPRING_SERVICES_USERNAME: admin
      SPRING_SERVICES_PASSWORD: admin123
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      ROUTING_KEY_ROOM_CREATED: room.created
      ROUTING_KEY_ROOM_UPDATED: room.update
      ROUTING_KEY_ROOM_DELETED: room.deleted
      EXCHANGE_ROOM_NAME: room.exchange
    depends_on:
      - eureka
      - rabbitmq
      - postgres-room
    ports:
      - "8083:8083"

  gateway:
    build: ./gateway
    container_name: gateway
    environment:
      EUREKA_URL: http://eureka:8761/eureka
    depends_on:
      - eureka
    ports:
      - "8080:8080"

  eureka:
    build: ./eureka
    container_name: eureka
    ports:
      - "8761:8761"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
        - redis_data:/data

  postgres-room:
    image: postgres
    container_name: postgres-room
    environment:
      POSTGRES_DB: room_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pg_data_room:/var/lib/postgresql/data


  postgres-employee:
    image: postgres
    container_name: postgres-employee
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - pg_data_employee:/var/lib/postgresql/data

  postgres-reservation:
    image: postgres
    container_name: postgres-reservation
    environment:
      POSTGRES_DB: reservation_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5434:5432"
    volumes:
      - pg_data_reservation:/var/lib/postgresql/data

volumes:
  redis_data:
  pg_data_room:
  pg_data_employee:
  pg_data_reservation: