spring:
  cloud:
    gateway:
      routes:
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            Path=/api/v1/reservation/**

        - id: employee-service
          uri: lb://employee-service
          predicates:
            Path=/api/v1/employee/**

        - id: room-service
          uri: lb://room-service
          predicates:
            Path=/api/v1/room/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            Path=/api/v1/auth/**