package com.br.thaua.reservation_service.domain;

public enum EventType {
    RESERVATION_CREATED,
    RESERVATION_UPDATED,
    RESERVATION_DELETED,
    RESERVATION_BEGIN,
    RESERVATION_FINISHED,
    RESERVATION_EMPLOYEE_PRESENT,
    RESERVATION_EMPLOYEE_NOT_PRESENT,
    ROOM_DELETED_APPROVE
}
