package com.br.thaua.employee_service.domain;

public enum EventType {
    AUTH_CREATED,
    AUTH_UPDATED,
    AUTH_DELETED,
    ROOM_FEEDBACK,
    ROOM_LIKED,
    ROOM_DELETED,
    RESERVATION_CREATED,
    RESERVATION_UPDATED,
    RESERVATION_DELETED,
    RESERVATION_EMPLOYEE_PRESENT,
    RESERVATION_EMPLOYEE_NOT_PRESENT
}
